
categories = [
    "Plant-based foods and beverages",
    "Plant-based foods",
    "Snacks",
    "Sweet snacks",
    "Beverages",
    "Dairies",
    "Cereals and potatoes",
    "Meats and their products",
    "Fermented foods",
    "Fermented milk products",
    "Fruits and vegetables based foods",
    "Condiments",
    "Meats",
    "Biscuits and cakes",
    "Desserts",
    "Meals",
    "Cereals and their products",
    "Spreads",
    "groceries",
    "Sauces",
    "Cheeses",
    "Confectioneries",
    "Breakfasts",
    "Frozen foods",
    "Prepared meats",
    "Plant-based beverages",
    "Vegetables based foods",
    "Cocoa and its products",
    "Canned foods",
    "Seafood",
    "Sweet spreads",
    "Fruits based foods",
    "Biscuits",
    "Dairy desserts",
    "Breads",
    "Plant-based spreads",
    "Fats",
    "Fishes and their products",
    "Fermented dairy desserts",
    "Fishes",
    "Pastas",
    "Salty snacks",
    "Alcoholic beverages",
    "Sweeteners",
    "Yogurts",
    "Seeds",
    "Legumes and their products",
    "Poultries",
    "Frozen desserts",
    "Cakes",
    "Vegetable fats",
    "Appetizers",
    "Canned plant-based foods",
    "Farming products",
    "Chocolates",
    "Vegetables",
    "Fruit-based beverages",
    "Nuts and their products",
    "Dried products",
    "Fatty fishes",
    "Vegetable oils",
    "Juices and nectars",
    "Hot beverages",
    "Bee products",
    "Chocolate candies",
    "Fruit and vegetable preserves",
    "Honeys",
    "Breakfast cereals",
    "Dietary supplements",
    "Carbonated drinks",
    "Legumes",
    "Chicken and its products",
    "Cow cheeses",
    "Olive tree products",
    "Fruits",
    "Chickens",
    "Candies",
    "Chips and fries",
    "Jams",
    "Hams",
    "Salted spreads",
    "Sodas",
    "Fruit juices",
    "Soups",
    "Milks",
    "Nuts",
    "Canned vegetables",
    "Crisps",
    "Sausages",
    "Cereal grains",
    "Ice creams and sorbets",
    "Dairy substitutes",
    "Teas",
    "Dried plant-based foods"
];
